# docker compose up -d --build

services:
    webserver:
        container_name: Webtrees_webserver
        restart: always
        build:
            context: .
        volumes:
            - ../webtrees:/var/www
            - ../webtrees_modules:/var/www/modules_v4
            - type: volume
              source: Webtrees-Data
              target: /var/www/data
              volume:
                nocopy: false
        ports:
            - "80:80"
            - "443:443"
        # note that in the php container the file /var/www/data/config.ini.php also refers to the URL

    php-fpm:
        container_name: Webtrees_php_fpm
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - ../webtrees:/var/www
            - ../webtrees_modules:/var/www/modules_v4
            - type: volume
              source: Webtrees-Data
              target: /var/www/data
              volume:
                nocopy: false

    database:
        container_name: Webtrees_maria_db
        image: mariadb
#        command: mysqld --user=root --verbose
#        restart: always
        environment:
            MYSQL_DATABASE: "webtrees"
            MYSQL_USER: "wt"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "root-password"
#            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
          - "3306:3306"
        volumes:
          - Webtrees-DB:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin
      container_name: Webtrees_pma
      tty: true
      depends_on:
        - database
      ports:
        - "8081:80"
      environment:
        PMA_HOST: Webtrees_maria_db
        PMA_ARBITRARY: 1
        PMA_PORT: 3306

networks:
  default:
    external: true
    name: Webtrees-Net

volumes:
    Webtrees-Data:
    Webtrees-DB:
